[workspace.package]
version = "0.1.0"
edition = "2024"
description = "guestpy is a Rust library for executing guest Python code transparently."
repository = "https://github.com/wizrds/guestpy"
license = "ISC"
readme = "README.md"

[workspace]
resolver = "2"
members = [
    "crates/guestpy-macros",
    "crates/guestpy-core",
    "crates/guestpy-rustpython",
    "crates/guestpy-pyo3",
    "crates/guestpy",
]
exclude = [
    "crates/guestpy-test",
]

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }

async-trait = { version = "0.1" }
futures = { version = "0.3" }

thiserror = { version = "2" }
proc-macro-crate = { version = "3.5" }

bytes = { version = "1" }
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1", features = ["serde", "v4"] }

tokio = { version = "1" }
tokio-util = { version = "0.7" }
include_dir = { version = "0.7" }
