[package]
name = "guestpy-pyo3"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true

[dependencies]
guestpy-core = { path = "../guestpy-core", version = "0.0.0", default-features = false }

thiserror = { workspace = true }

pyo3 = { version = "0.29", features = ["macros"] }

[features]
default = []

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt", "time"] }
